# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    #bundles:        [ ]
    filters:
        #cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [%node_modules_path%]
        #yui_css:
        #    jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        #yui_js:
        #    jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar

#    assets:
#         js_bootstrap:
#             inputs:
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js'
#                 - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js'