imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: oauth.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: "%kernel.root_dir%/sessions/"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    form:
        resources:
            - 'letskickinFrontBundle:Form:fields.html.twig'

    paths:
        "%kernel.root_dir%/../src/letskickin/FrontBundle/Resources/views/layouts": Layouts
        "%kernel.root_dir%/../src/letskickin/FrontBundle/Resources/views/blocks": Blocks

    globals:
        site:
            locale: %locale%
            diagnostic_mode: false
            #sitemap: "/sitemap.xml"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    #bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [%node_modules_path%]
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: letskickin\BackBundle\Entity\User