# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    paths:
        "%kernel.root_dir%/Resources/views": Views
        "%kernel.root_dir%/Resources/layouts": Layouts
        "%kernel.root_dir%/Resources/blocks": Blocks

    globals:
        site:
            locale: %locale%
            diagnostic_mode: false
            #sitemap: "/sitemap.xml"

        # google:
        #     verification_code: %google_verification_code%
        #     ga_code: %google_ga_code%
