# STATIC PAGES
landingpage:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'letskickinFrontBundle:Static:landing.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400

privacy:
    pattern:  /legal/privacy/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'letskickinFrontBundle:Static:privacy.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400

terms:
    pattern:  /legal/terms/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'letskickinFrontBundle:Static:terms.html.twig'
        maxAge: 86400
        sharedMaxAge: 86400

# POTS
pot_create:
    pattern:  /pots/wizard/
    defaults: { _controller: letskickinBackBundle:Pot:createPot }

pot_confirm:
    pattern:  /pots/confirm/{pot_key}
    defaults: { _controller: letskickinBackBundle:Pot:confirmPot, pot_key: null }

pot_notify:
    pattern:  /pots/notify/{pot_key}/{participant_key}
    defaults: { _controller: letskickinBackBundle:Pot:notifyPot, pot_key: null }

pot_show:
    pattern:  /{pot_key}
    defaults: { _controller: letskickinBackBundle:Pot:showPot, pot_key: null }

pot_admin:
    pattern: /pots/edit/{pot_key}
    defaults: { _controller: letskickinBackBundle:Pot:adminPot, pot_key: null }

participant_admin:
    pattern: /participant/{participant_key}
    defaults: { _controller: letskickinBackBundle:Pot:adminParticipant, participant_key: null }

#FosUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern:  /login/check-facebook

# google_login:
#     pattern:  /login/check-google