#FosUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

# google_login:
#     pattern: /login/check-google


# POTS
pot_create:
    pattern:  /pots/wizard
    defaults: { _controller: letskickinBackBundle:Pot:createPot }

pot_confirmed:
    pattern:  /pots/confirm/{pot_key}/{admin_key}
    defaults: { _controller: letskickinBackBundle:Pot:potConfirmed, admin_key: null }

pot_show:
    pattern:  /pots/{pot_key}/{admin_key}
    defaults: { _controller: letskickinBackBundle:Pot:showPot, admin_key: null }