parameters:
    letskickin.user_provider.class: letskickin\BackBundle\Security\Core\User\FOSUBUserProvider
    letskickin.form.create_pot.flow: letskickin\BackBundle\Form\potFlow

    letskickin.manager.pot_manager: letskickin\BackBundle\Doctrine\PotManager
    letskickin.manager.pot_class: letskickin\BackBundle\Entity\Pot
    letskickin.subscriber.pot: letskickin\BackBundle\EventListener\PotSubscriber

    letskickin.manager.participant_manager: letskickin\BackBundle\Doctrine\ParticipantManager
    letskickin.manager.participant_class: letskickin\BackBundle\Entity\Participant

services:
    letskickin.form.flow.createPot:
        class: "%letskickin.form.create_pot.flow%"
        parent: craue.form.flow
        scope: request

    letskickin.manager.pot:
        class: "%letskickin.manager.pot_manager%"
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: "%letskickin.manager.pot_class%"

    letskickin.manager.participant:
        class: "%letskickin.manager.participant_manager%"
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: "%letskickin.manager.participant_class%"

    letskickin.subscriber.pot:
        class: "%letskickin.subscriber.pot%"
        arguments:
            mailer: "@mailer"
            container: "@templating"
        tags:
            - { name: kernel.event_subscriber }
