parameters:
    letskickin.user_provider.class: letskickin\BackBundle\Security\Core\User\FOSUBUserProvider
    letskickin.form.create_pot.type: letskickin\BackBundle\Form\CreatePotForm
    letskickin.form.create_pot.flow: letskickin\BackBundle\Form\CreatePotFlow

    letskickin.manager.pot_manager: letskickin\BackBundle\Doctrine\PotManager
    letskickin.manager.pot_class: letskickin\BackBundle\Entity\Pot
    letskickin.listener.pot: letskickin\BackBundle\EventListener\PotListener

#    letskickin.manager.guest_manager: letskickin\BackBundle\Doctrine\GuestManager
#    letskickin.manager.guest_class: letskickin\BackBundle\Entity\Guest
#    letskickin.listener.guest: letskickin\BackBundle\EventListener\GuestListener

services:
    letskickin.user_provider:
        class: "%letskickin.user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        # arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]

    letskickin.form.createPot:
        class: "%letskickin.form.create_pot.type%"
        tags:
            - { name: form.type, alias: createPot }

    letskickin.form.flow.createPot:
        class: "%letskickin.form.create_pot.flow%"
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ @letskickin.form.createPot ] ]

    letskickin.manager.pot:
        class: "%letskickin.manager.pot_manager%"
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: "%letskickin.manager.pot_class%"

    letskickin.listener.pot_created:
        class: "%letskickin.listener.pot%"
        arguments:
            mailer: "@mailer"
        tags:
            - { name: kernel.event_subscriber, event: letskickin.pot.created, method: onCreatePotEvent }



#    letskickin.manager.guest:
#        class: "%letskickin.manager.guest_manager%"
#        arguments:
#            dispatcher: "@event_dispatcher"
#            em: "@doctrine.orm.entity_manager"
#            class: "%letskickin.manager.guest_class%"

#    letskickin.listener.pot.guest_added:
#        class: "%letskickin.listener.guest%"
#        arguments:
#            mailer: "@mailer"
#        tags:
#            - { name: kernel.event_listener, event: letskickin.pot.guest_added, method: onAddGuestEvent }