letskickin\BackBundle\Entity\Pot:
    properties:
        occasion:
            - NotBlank: { message: "pot.occasion.not_blank" }
            - Length:
                min: 5
        admin_name:
            - NotBlank: ~
            - Length:
                min: 2
        admin_email:
            - NotBlank: ~
            - Email:
                checkMX: true
        deadline:
            - NotBlank: ~
            - Date: ~
        amount_total:
            - NotBlank: ~
        amount_partial:
            - NotBlank: ~
        # notifications_active:
        # guests_invite:
        # reminders_active:
        # tracking_active:
        # message: