parameters:
    letskickin_extension.class: letskickin\FrontBundle\Twig\LetskickinExtension

services:
    letskickin.twig.letskickin_extension:
        class: %letskickin_extension.class%
        tags:
            - { name: twig.extension }