parameters:
#    letskickin_front.example.class: letskickin\FrontBundle\Example

services:
#    letskickin_front.example:
#        class: %letskickin_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
